version: "3"

services:
  db:
    build:
      context: .
      target: "development"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./users_db:/users_db
      - ./scripts:/scripts
      - ./tests:/tests
    depends_on:
      - postgres
  
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "54321:5432"