"""role_permission permission unique

Revision ID: 2114b71ae0e7
Revises: 3eb311d1aec7
Create Date: 2023-03-31 13:36:55.632501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2114b71ae0e7"
down_revision = "3eb311d1aec7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "role_permissions", ["permission"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role_permissions", type_="unique")
    # ### end Alembic commands ###
